### ISSUE TITLE
Register Dataset thumbnail files at data ingest

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-pipeline#328]
For all datasets if the file, extras/thumbnail.jpg exists register it as a file to be published via the assets service.

**Comment by yuanzhou** [comment]
Notes: 
- For primary dataset, not the secondary
- It happens when the Submit button is hit (the dataset metadata information is already created), not through the ingest UI though. The `extras/thumbnail.jpg ` will be uploaded via Globus with the data files. 
- I'll need to look for `extras/thumbnail.jpg` and register it then commit it. Will decide the workflow.
- Create a new branch off `devel` and send a PR back to `devel` with Joel as the reviewer. 
- Code: https://github.com/hubmapconsortium/ingest-pipeline/blob/devel/src/ingest-pipeline/airflow/dags/utils.py#L934
- Test the work against Airflow on STAGE

**Comment by yuanzhou** [comment]
Updates:
- Use `dataset_lz_path_fun` (https://github.com/hubmapconsortium/ingest-pipeline/blob/devel/src/ingest-pipeline/airflow/dags/utils.py#L875) to get the full path to the dataset
- Check the existence of `extra/thumbnail.jpg` under the dataset  full path
- Add the full thumbnail file path to something like `md['thumbnail_path'] = path` to be sent back to ingest-api
- `Dataset.get_dataset_ingest_update_record()` (https://github.com/hubmapconsortium/ingest-api/blob/790adaa789a6378b4385d79e6e6bd78ba10023f2/src/dataset.py#L194) parses the resulting data from ingest-pipeline and send the updated dataset record to entity-api to store the information in Neo4j
- Add a new property in entity-api schema yaml for `Dataset.thumbnail_image` with trigger methods to get back the tmp id then commit the file to get back file_uuid. The copy of this thumbnail image will be under the `hive/hubmap/hm_uploads/<dataset_uuid>/<file_uuid>`
- The ingest-api will also need to create a symbolic link from this `hive/hubmap/hm_uploads/<dataset_uuid>/<file_uuid>` to the assets `hive/hubmap/assets/<file_uuid>` but without the dataset_uuid directory to avoid conflicts.
- Then this thumbnail file will be accessible via the assets file service. Token is needed if the dataset is consortium, public dataset doesn't require a token.
