### ISSUE TITLE
Talk with joel and get ingest-validation-tools into pipeline

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-pipeline#44]

**Comment by mccalluc** [comment]
@jswelling : I think you are using ingest-validation-tools for for TSV validation, and you are aware of how it could be used to validate directory structures, if we could communicate that to the labs, instead of needing to deal with _de facto_ submission? I think this could be closed, but let me know if you think there is any work for me here?

**Comment by jswelling** [comment]
Closed as obsolete.
