### ISSUE TITLE
Define a file information structure that can handle sending thousands of file names to the Portal.

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-pipeline#72]
CODEX (and possible other assays) have uploaded datasets with thousands of files. Passing these long lists of files to display in the portal interface is problematic. These may include the raw data that we need to make available for download, or outputs from TMC processing pipelines that were uploaded with the raw data. How do we make these files available through the portal?

**Comment by mccalluc** [comment]
For me, it sounds like there are two sides of this: knowing more about what information you can provide, and knowing more about how we would want to handle it downstream. Some initial questions:
- It sounds like we need to be able to accommodate large arbitrary sets: Some sets might have a structure like sequential integers or a tidy hierarchy, but that's not something we can depend on? Or should we attack a particular simpler, less general case, even if it won't handle everything that might come down the line?
- Sorry if you've already provided this, but can you point us to a few of these files in a way that we can access them? I'll loop in Ilan because he knows a lot more about the underlying formats.
- If there isn't a predictable structure which allows us to reconstruct urls from a little information, would it be possible to index them into some database or elasticsearch? We'd still need to clarify how we'd intend to use it, to know how to index it appropriately.

**Comment by mccalluc** [comment]
As far as I know, specifying the subset of files that should be displayed has fixed this problem. Closing this and #64.
